---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v0.1.0)"
        required: true
        type: string
  push:
    tags:
      - "v*"

jobs:
  tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tag and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ## Needed to fetch tags
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          mkdir -p dist

          declare -a BuildPlatforms=("darwin/amd64" "darwin/arm64" "linux/amd64" "linux/arm64" "windows/amd64")

          for platform in "${BuildPlatforms[@]}"; do
            GOOS=${platform%/*}
            GOARCH=${platform#*/}
            export GOOS GOARCH

            OS_NAME=$GOOS
            if [ "$GOOS" = "darwin" ]; then OS_NAME="macOS"; fi

            BIN_NAME="b2cleaner"
            if [ "$GOOS" = "windows" ]; then
              BIN_NAME="b2cleaner.exe"
            fi

            go build -o dist/$BIN_NAME ./cmd/b2cleaner

            ZIP_NAME="b2cleaner-${{ github.event.inputs.version }}-${OS_NAME}-${GOARCH}.zip"
            zip -j dist/$ZIP_NAME dist/$BIN_NAME
            rm dist/$BIN_NAME
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create Github release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
